### ISSUE TITLE
Sphinx - NotImplementedError: analogio not supported for this board.

### ISSUE THREAD

**Issue by Gadgetoid** [pimoroni/Pimoroni_CircuitPython_MICS6814#1]
The Sphinx documentation build fails with the following error:

```
Warning, treated as error:
autodoc: failed to import module 'pimoroni_mics6814'; the following exception was raised:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 66, in import_module
    return importlib.import_module(modname)
  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/runner/work/Pimoroni_CircuitPython_MICS6814/Pimoroni_CircuitPython_MICS6814/pimoroni_mics6814.py", line 29, in <module>
    import analogio
  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/analogio.py", line 21, in <module>
    raise NotImplementedError("analogio not supported for this board.")
NotImplementedError: analogio not supported for this board.
```

I'm not sure if I should work around this- by mocking the relevant library in the Sphinx config- or if this just isn't The Done Thing for CircuitPython libraries. The `analogio` and `digitalio` imports are used to configure input pins:

https://github.com/pimoroni/Pimoroni_CircuitPython_MICS6814/blob/602826b79339ab7caa5f5fd95c678e0a4135258d/pimoroni_mics6814.py#L58-L66

But, perhaps, the CircuitPythonic thing to do would be to expect the user to pre-configure these pins and pass in the digitalio and analogio objects?

**Comment by Gadgetoid** [comment]
Potential fix (thank you kattni) is to use `autodoc_mock_imports` to mock `analogio` cleanly and squash this error - https://github.com/adafruit/Adafruit_CircuitPython_CircuitPlayground/blob/a0692dfbdd05ff0bfbcbad7294ac9c6f694b0404/docs/conf.py#L29

It looks like the correct approach - or at least the one with a precedent (thanks again kattni) - is to accept pins of a specific type (`analogio.AnalogIn` and `digitalio.DigitalIn`) rather than a raw pin object.

See: 

https://github.com/adafruit/Adafruit_CircuitPython_CharLCD/blob/a9e0c61575e02fe6b5eea348553f1e92d1f55632/adafruit_character_lcd/character_lcd.py#L117-L150

With usage example:

https://github.com/adafruit/Adafruit_CircuitPython_CharLCD/blob/master/examples/charlcd_rgb_simpletest.py

**Comment by Gadgetoid** [comment]
Might want to- potentially- add type checking to `__init__`. And certainly some docstrings.

**Comment by tannewt** [comment]
I don't recommend type checking actually. Instead, you can check for the APIs you use. (`hasattr(pin, "value")`)

This approach allows the driver to be used with an external ADC too. `analogio` is exclusively native and should only be required by native code that uses that fact.
